

#define OFFSETFACTORX0 				0x44e0
#define OFFSETFACTORX1 				OFFSETFACTORX0+4
#define OFFSETFACTORY0 				OFFSETFACTORX0+8
#define OFFSETFACTORY1  			OFFSETFACTORX0+12
#define OFFSETMINIMUM      			OFFSETFACTORX0+16
#define OFFSETTIMEPRIMARY			OFFSETFACTORX0+20
#define OFFSETTIMESECONDARY			OFFSETFACTORX0+24
#define OFFSETTIMETERTIARY			OFFSETFACTORX0+28


#define OFFSETCMD0        			OFFSETFACTORX0+32
#define OFFSETCMD1         			OFFSETCMD0+255
#define OFFSETCMD2         			OFFSETCMD0+255*2
#define OFFSETCMD3         			OFFSETCMD0+255*3
#define OFFSETCMD4         			OFFSETCMD0+255*4
#define OFFSETCMD5         			OFFSETCMD0+255*5
#define OFFSETCMD6         			OFFSETCMD0+255*6
#define OFFSETCMD7         			OFFSETCMD0+255*7
#define OFFSETCMD8         			OFFSETCMD0+255*8


#define OFFSETFACTORSFORWHEEL 		OFFSETFACTORX0+2327
#define OFFSETSCROLLMOUSEDOWN 		OFFSETFACTORX0+2328
#define OFFSETSWALLOWCLICK	 		OFFSETFACTORX0+2336